apiVersion: v1
kind: ConfigMap
metadata:
  name: java-configmap
  namespace: dev
  labels:
    app.kubernetes.io/name: java-app
stringData:
  MYSQL_HOST: "mysql-service"
  MYSQL_PORT: "3306"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
