apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-ingress
  namespace: dev
  labels:
    app.kubernetes.io/name: java-app
spec:
  ingressClassName: traefik
  rules:
  - host: "java.app.local"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: java-service
            port:
              number: 80
