apiVersion: v1
kind: ServiceAccount
metadata:
  name: java-sa
  namespace: dev
  labels:
    app.kubernetes.io/name: java-app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: java-role
  namespace: dev
  labels:
    app.kubernetes.io/name: java-app
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: java-rolebinding
  namespace: dev
  labels:
    app.kubernetes.io/name: java-app
subjects:
- kind: ServiceAccount
  name: java-sa
  namespace: dev
roleRef:
  kind: Role
  name: java-role
  apiGroup: rbac.authorization.k8s.io
