apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment # Deployment object name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go # Deployment looks for pods with this label
  template:
    metadata:
      labels:
        app: go # Created Pods will have this label
    spec:
      containers:
      - name: go-container
        image: golang:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"