apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-ingress
  namespace: dev
  labels:
    app.kubernetes.io/name: go-app
spec:
  ingressClassName: traefik
  rules:
  - host: "go.app.local"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: go-service
            port:
              number: 80
