apiVersion: v1
kind: Secret
metadata:
  name: go-secret
  namespace: dev
  labels:
    app.kubernetes.io/name: go-app
type: Opaque
stringData:
  MYSQL_USERNAME: "appuser"
  MYSQL_PASSWORD: "123456"
  REDIS_USERNAME: "appuser"
  REDIS_PASSWORD: "foobared"
