apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: dev
  labels:
    app.kubernetes.io/name: go-app
spec:
  type: ClusterIP
  selector:
    app: go-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
